
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50


arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - base_joint
    - shoulder
    - elbow
    - wrist
  gains:
    base_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    shoulder:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    elbow:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
